version: '3.8'

services:
  # -------------------------------------------------------
  # 1. GATEWAY (Traefik)
  # -------------------------------------------------------
  gateway:
    image: traefik:v2.10
    container_name: api_gateway
    command:
      - "--api.insecure=true" # Activate the insecure API (Dashboard)
      - "--providers.docker=true" # Activate Docker provider
      - "--providers.docker.exposedbydefault=false" # Allow only explicitly enabled containers
      - "--entrypoints.web.address=:80" # Define entrypoint for HTTP
      - "--metrics.prometheus=true"  # Bật Prometheus metrics
      - "--entrypoints.metrics.address=:8082" # Mở cổng metrics riêng (nếu muốn)
    ports:
      - "8080:80"      # API Gateway
      - "8081:8080"    # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - app_network

  # -------------------------------------------------------
  # 2. USER SERVICE
  # -------------------------------------------------------
  user-service:
    build:
      context: ./task_management/user-service
      dockerfile: Dockerfile
    container_name: user-service
    expose:
      - "8000"
    ports:
      - "8010:8000"
    volumes:
      - ./task_management/user-service:/app # Source code of the app
      - /app/.venv
    environment:
      - WATCHFILES_FORCE_POLLING=true
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - REDIS_URL=${REDIS_URL}
      - FIRST_SUPERUSER=${FIRST_SUPERUSER}
      - FIRST_SUPERUSER_PASSWORD=${FIRST_SUPERUSER_PASSWORD}
      - TZ=Asia/Ho_Chi_Minh
      - OTEL_SERVICE_NAME=user-service         
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4317 
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - app_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.user.rule=PathPrefix(`/user`)"
      - "traefik.http.routers.user.middlewares=user-strip@docker"
      - "traefik.http.middlewares.user-strip.stripprefix.prefixes=/user"
      - "traefik.http.services.user.loadbalancer.server.port=8000"

      # Config Rate Limiting Middleware
      # 1. Middleware
      - "traefik.http.middlewares.limit-ip.ratelimit.average=100"
      - "traefik.http.middlewares.limit-ip.ratelimit.burst=50"

      # 2. Router 
      - "traefik.http.routers.user.middlewares=user-strip@docker,limit-ip@docker"
    healthcheck:
      test: ["CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health').getcode() == 200"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  # -------------------------------------------------------
  # 3. TASK SERVICE
  # -------------------------------------------------------
  task-service:
    build:
      context: ./task_management/task-service
      dockerfile: Dockerfile
    container_name: task-service
    expose:
      - "8000"
    ports:
      - "8020:8000"
    volumes:
      - ./task_management/task-service:/app # Source code of the app
      - /app/.venv    
    environment:
      - WATCHFILES_FORCE_POLLING=true
      - DATABASE_URL=${TASK_DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    
    networks:
      - app_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.task.rule=PathPrefix(`/task`)"
      - "traefik.http.routers.task.middlewares=task-strip@docker"
      - "traefik.http.middlewares.task-strip.stripprefix.prefixes=/task"
      - "traefik.http.services.task.loadbalancer.server.port=8000"
    healthcheck:
      test: ["CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health').getcode() == 200"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  # -------------------------------------------------------
  # 4. NOTIFICATION SERVICE
  # -------------------------------------------------------
  notification-service:
    build:
      context: ./task_management/notification-service
      dockerfile: Dockerfile
    container_name: notification-service
    expose:
      - "8000"
    ports:
      - "8030:8000"
    volumes:
      - ./task_management/notification-service:/app # Source code of the app
      - /app/.venv     
    environment:
      - WATCHFILES_FORCE_POLLING=true
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092 # Cổng nội bộ
      - OTEL_SERVICE_NAME=notification-service # Tên hiển thị trên Tempo
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4317
      - TZ=Asia/Ho_Chi_Minh
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - app_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.notification.rule=PathPrefix(`/notification`)"
      - "traefik.http.routers.notification.middlewares=notification-strip@docker"
      - "traefik.http.middlewares.notification-strip.stripprefix.prefixes=/notification"
      - "traefik.http.services.notification.loadbalancer.server.port=8000"
    healthcheck:
      test: ["CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health').getcode() == 200"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  # -------------------------------------------------------
  # 5. POSTGRESQL DATABASE
  # -------------------------------------------------------
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app_network

  # -------------------------------------------------------
  # 6. ZOOKEEPER 
  # ------------------------------------------------------- 
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: "echo stat | nc localhost 2181 || exit 1"
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - app_network
  # -------------------------------------------------------
  # 7. KAFKA BROKER
  # -------------------------------------------------------
  kafka:
    image: confluentinc/cp-kafka:7.3.2
    ports:
      - '9092:9092'
      - '29092:29092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_INTERNAL://:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "cub", "kafka-ready", "-b", "localhost:9092", "1", "20"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - app_network
  # -------------------------------------------------------
  # 8. REDIS (Caching/Blacklisting/WebSocket State)
  # -------------------------------------------------------
  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
    networks:
      - app_network
  # -------------------------------------------------------
  # 9. PROMETHEUS (Thu thập số liệu)
  # -------------------------------------------------------
  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: prometheus
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - app_network

  # -------------------------------------------------------
  # 10. GRAFANA (Vẽ biểu đồ)
  # -------------------------------------------------------
  grafana:
    image: grafana/grafana:10.0.0
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      
      - ./docker/grafana/provisioning:/etc/grafana/provisioning
      
      # 2. Nạp file JSON biểu đồ vào đúng chỗ dashboard.yml trỏ tới
      - ./docker/grafana/dashboards_json:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin 
    networks:
      - app_network
    depends_on:
      - prometheus
# -------------------------------------------------------
# 11. LOKI + PROMTAIL (Logging)
# -------------------------------------------------------
  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100" #http port: http://loki:3100
    volumes:
      - ./docker/loki/local-config.yaml:/etc/loki/local-config.yaml
    restart: unless-stopped
    networks:
      - app_network


#-------------------------------------------------------
# 12. PROMTAIL (Log shipper)
# -------------------------------------------------------
  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail
    volumes:
      # Mount file cấu hình
      - ./docker/promtail/config.yml:/etc/promtail/config.yml
      # Mount socket docker để đọc log các container khác
      - /var/run/docker.sock:/var/run/docker.sock
      # Mount thư mục log docker
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: -config.file=/etc/promtail/config.yml  
    depends_on:
      - loki
    restart: unless-stopped
    networks:
      - app_network
# -------------------------------------------------------
# 13. TEMPO (Distributed Tracing)
# -------------------------------------------------------
  tempo:
    image: grafana/tempo:2.2.0
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./docker/tempo/tempo.yaml:/etc/tempo.yaml
    ports:
      - "3200:3200" #  http://tempo:3200
      - "4317:4317" # Cổng OTLP gRPC để Code Python bắn Trace vào
    networks:
      - app_network
# -------------------------------------------------------
# 14. KAFKA UI (Giao diện quản lý Kafka)
# -------------------------------------------------------
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8090:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    networks:
      - app_network
    depends_on:
      - kafka
networks:
  app_network:
    driver: bridge
volumes:
  postgres_data:
  redis_data:
  prometheus_data:
  grafana_data: