version: '3.8'

services:
  # -------------------------------------------------------
  # 1. GATEWAY (Traefik)
  # -------------------------------------------------------
  gateway:
    image: traefik:v2.10
    container_name: api_gateway
    command:
      - "--api.insecure=true" # Kích hoạt dashboard không bảo mật
      - "--providers.docker=true" # Kích hoạt nhà cung cấp Docker
      - "--providers.docker.exposedbydefault=false" # Chỉ lộ các dịch vụ được gắn nhãn
      - "--entrypoints.web.address=:80" # Định nghĩa entrypoint web trên cổng 80
    ports:
      - "8080:80"      # API chính
      - "8081:8080"    # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - app_network

  # -------------------------------------------------------
  # 2. USER SERVICE
  # -------------------------------------------------------
  user-service:
    build:

      context: ./task_management/user-service
      dockerfile: Dockerfile

    container_name: user-service

    ports:
      - "8000:8000"
    volumes:
      - ./task_management/user-service:/app # Mã nguồn ứng dụng
      - /app/.venv      # Bức tường bảo vệ thư viện (Quan trọng)
    environment:
      - WATCHFILES_FORCE_POLLING=true
    
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    
    networks:
      - app_network
    labels:
      - "traefik.enable=true" # Kích hoạt Traefik cho dịch vụ này
      - "traefik.http.routers.fastapi.rule=PathPrefix(`/user`)"
      - "traefik.http.services.fastapi.loadbalancer.server.port=8000"

  # -------------------------------------------------------
  # 3. TASK SERVICE
  # -------------------------------------------------------
  task-service:
    build:

      context: ./task_management/task-service
      dockerfile: Dockerfile

    container_name: task-service

    ports:
      - "8000:8000"
    volumes:
      - ./task_management/task-service:/app # Mã nguồn ứng dụng
      - /app/.venv      # Bức tường bảo vệ thư viện (Quan trọng)
    environment:
      - WATCHFILES_FORCE_POLLING=true
    
    command: uvicorn app.main:app --host 0.0.0.0 --port 8010 --reload
    
    networks:
      - app_network
    labels:
      - "traefik.enable=true" # Kích hoạt Traefik cho dịch vụ này
      - "traefik.http.routers.fastapi.rule=PathPrefix(`/task`)"
      - "traefik.http.services.fastapi.loadbalancer.server.port=8000"

  # -------------------------------------------------------
  # 4. NOTIFICATION SERVICE
  # -------------------------------------------------------
  notification-service:
    build:

      context: ./task_management/notification-service
      dockerfile: Dockerfile

    container_name: notification-service

    ports:
      - "8000:8000"
    volumes:
      - ./task_management/notification-service:/app # Mã nguồn ứng dụng
      - /app/.venv      # Bức tường bảo vệ thư viện (Quan trọng)
    environment:
      - WATCHFILES_FORCE_POLLING=true
    
    command: uvicorn app.main:app --host 0.0.0.0 --port 8020 --reload
    
    networks:
      - app_network
    labels:
      - "traefik.enable=true" # Kích hoạt Traefik cho dịch vụ này
      - "traefik.http.routers.fastapi.rule=PathPrefix(`/notification`)"
      - "traefik.http.services.fastapi.loadbalancer.server.port=8000"

networks:
  app_network:
    driver: bridge