global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'fastapi_microservices'
    metrics_path: '/metrics'  # Python dùng đường dẫn này (Java dùng /actuator/prometheus)
    static_configs:
      - targets: ['user-service:8000', 'task-service:8000', 'notification-service:8000'] 
        # Tên service phải khớp với docker-compose.yml của bạn

  - job_name: 'traefik'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['gateway:8080']