global:
  scrape_interval: 3s     
  evaluation_interval: 3s

scrape_configs:
  - job_name: 'fastapi_microservices'
    metrics_path: '/metrics'
    static_configs:
      - targets: 
        - 'user-service:8000'
        - 'task-service:8000'         
        - 'notification-service:8000' 
        
    relabel_configs:
      - source_labels: [__address__]
        regex: '([^:]+)(?::\d+)?'
        target_label: app_name

  - job_name: 'traefik'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['gateway:8082']